### ISSUE TITLE
Have the data arrive at current year and month 

### ISSUE THREAD

**Issue by carlitos-206** [carlitos-206/backEndUWFinal2022#85]
when arriving the data has been set to arrive a jan 2014, have it return on arrival most current data

**Comment by khanhqhoang** [comment]
Not so sure why it is needed.  Currently the default of the drop down is current month and year which is Sep 2022 presently.  I also put a noted on the page: the data set is valid from Jul 2014 to Sep 2022.  If user selects a no data combination of month and year then there is no data and s/he can try another combination of month and year.  Since this is might be a enhancement feature only, i would not rather spending time on it at this point.  Just focus on the primary functionalities we need to complete for the presentation. I will flag this as may be but not required at this point.
